### ISSUE TITLE
Rounded corners not working

### ISSUE THREAD

**Issue by ConnyCola** [Funkenjaeger/brd2json#1]
Hi funkenjaeger, first of all thanks a lot for all your work in porting this tool to Eagle! I highly appreciate the work you put into this. 
I did discover several smaller problems for which I would start individual issues (hope this is fine for you). I noticed that rounded corners in the board outline as well as in just normal vector text as in silkscreen is not rendered correct in the html file. 
Please let me know if I can help fix this.

![image](https://user-images.githubusercontent.com/2567759/107719039-921bdc80-6cd7-11eb-8918-bc5599ac3ba3.png)
![image](https://user-images.githubusercontent.com/2567759/107719054-9942ea80-6cd7-11eb-937e-024bc57a2763.png)

[round_test.zip](https://github.com/Funkenjaeger/brd2json/files/5969210/round_test.zip)

**Comment by Funkenjaeger** [comment]
Thank you for submitting these reports!  I'm glad to see someone else using the tool.
In its current state it would probably be best characterized as an alpha level of maturity, and I haven't put a wide variety of board designs through it yet myself, so I appreciate the help identifying issues - and I'm certainly not opposed to suggested fixes either.

I'll take a look at the issues you've reported so far over the weekend.

**Comment by Funkenjaeger** [comment]
Thanks for the fix! (#5)
